name: OpenWrt image builder
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Init
      env:
        DEBIAN_FRONTEND: noninteractive
        DOWNLOAD_URL: https://downloads.openwrt.org/releases/21.02.3/targets/ramips/mt7620/openwrt-imagebuilder-21.02.3-ramips-mt7620.Linux-x86_64.tar.xz
        
      run: |
        sudo apt-get install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python
        wget -O /tmp/imagebuilder.tar.xz $DOWNLOAD_URL
        xz -d /tmp/imagebuilder.tar.xz
        tar -C /tmp -xvf /tmp/imagebuilder.tar
    - name: Build
      run: |
        cd /tmp/$(ls /tmp | grep 'openwrt-imagebuilder')
        #make image PROFILE="wt3020" PACKAGES="luci-i18n-base-zh-cn"
        make info
        cp -r bin /tmp
    - name : Upload
      uses: actions/upload-artifact@master
      with:
        name: image
        path: /tmp/bin
