name: OpenWrt image builder

on: 
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Init
      env:
        DEBIAN_FRONTEND: noninteractive
        DOWNLOAD_URL: https://downloads.openwrt.org/releases/21.02.3/targets/ramips/mt7620/openwrt-imagebuilder-21.02.3-ramips-mt7620.Linux-x86_64.tar.xz
      run: |
        sudo apt-get install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python
        wget -qO /tmp/imagebuilder.tar.xz $DOWNLOAD_URL && tar -C /tmp -xf /tmp/imagebuilder.tar.xz

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      if: github.event.inputs.ssh == 'true'

    - name: Build
      run: |
        cd /tmp/*openwrt-imagebuilder*
        sed '/read-only/d' /tmp/*openwrt*/target/linux/ramips/dts/*wt3020-8m*.dts
        make image PROFILE="nexx_wt3020-8m" PACKAGES="luci-i18n-base-zh-cn"
        mkdir /tmp/upload && cp -r bin/targets/*/*/* /tmp/upload
        echo "DEVICE_NAME=nexx_wt3020-8m" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name : Upload
      uses: actions/upload-artifact@master
      with:
        name: openwrt_${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: /tmp/upload
